# Generated by Django 4.2.6 on 2023-10-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerCity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='descrizione',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
