# Generated by Django 4.2.6 on 2023-10-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerCity', '0002_burger_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='descrizione',
            field=models.CharField(max_length=800),
        ),
    ]
