# Generated by Django 4.2.6 on 2023-10-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerCity', '0003_alter_burger_descrizione'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('userQuestion', models.CharField(max_length=800)),
            ],
        ),
    ]
